name: Build all Java to DEX

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout do código
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2️⃣ Instalar Java 8
    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # 3️⃣ Compilar todos os arquivos .java
    - name: Compile all Java files
      run: |
        mkdir -p bin
        find . -name "*.java" > sources.txt
        javac -source 1.8 -target 1.8 -d bin @sources.txt

    # 4️⃣ Baixar build-tools e pegar d8.jar
    - name: Download Android build-tools and extract d8.jar
      run: |
        mkdir -p tools
        wget https://dl.google.com/android/repository/build-tools_r33.0.2-linux.zip -O build-tools.zip
        unzip -q build-tools.zip
        cp build-tools/33.0.2/lib/d8.jar tools/
        rm -rf build-tools build-tools.zip

    # 5️⃣ Converter .class para .dex usando d8.jar
    - name: Convert classes to DEX
      run: |
        mkdir -p dex_output
        java -jar tools/d8.jar --min-api 21 --output=dex_output bin/**/*.class

    # 6️⃣ Upload do classes.dex
    - name: Upload classes.dex
      uses: actions/upload-artifact@v4
      with:
        name: dex-files
        path: ./dex_output/classes.dex
