name: Build all Java to DEX

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Pegar o código do repositório
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2️⃣ Instalar Java 8
    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # 3️⃣ Compilar todos os arquivos .java
    - name: Compile all Java files
      run: |
        mkdir -p bin
        find . -name "*.java" > sources.txt
        javac -source 1.8 -target 1.8 -d bin @sources.txt

    # 4️⃣ Baixar e extrair Android build-tools (inclui d8 nativo)
    - name: Download Android build-tools
      run: |
        mkdir -p android-sdk
        wget https://dl.google.com/android/repository/build-tools_r33.0.2-linux.zip -O android-build-tools.zip
        unzip -q android-build-tools.zip -d android-sdk
        rm android-build-tools.zip
        chmod +x android-sdk/33.0.2/d8

    # 5️⃣ Converter .class para .dex usando d8 nativo
    - name: Convert classes to DEX
      run: |
        mkdir -p dex_output
        ./android-sdk/33.0.2/d8 --min-api 21 --output=dex_output bin/**/*.class

    # 6️⃣ Upload do classes.dex como artefato
    - name: Upload classes.dex
      uses: actions/upload-artifact@v4
      with:
        name: dex-files
        path: ./dex_output/classes.dex
