name: Build all Java to DEX

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Pegar o código do repositório
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2️⃣ Instalar Java 8
    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # 3️⃣ Compilar todos os arquivos .java
    - name: Compile all Java files
      run: |
        mkdir -p bin
        find . -name "*.java" > sources.txt
        javac -source 1.8 -target 1.8 -d bin @sources.txt

    # 4️⃣ Configurar Android SDK e build-tools
    - name: Set up Android SDK
      uses: android/setup-sdk@v2
      with:
        api-level: 33
        build-tools: 33.0.2

    # 5️⃣ Converter todos os .class para .dex
    - name: Convert classes to DEX
      run: |
        mkdir -p dex_output
        d8 --min-api 21 --output=dex_output bin/**/*.class

    # 6️⃣ Upload do .dex como artefato
    - name: Upload classes.dex
      uses: actions/upload-artifact@v4
      with:
        name: dex-files
        path: ./dex_output/classes.dex
