name: Build ZipUtil.java to DEX

on:
  push:
    branches: [ main ]  # ou qualquer branch que desejar
  workflow_dispatch:   # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Compile Java source
      run: javac -source 1.8 -target 1.8 ZipUtil.java

    - name: Install Android SDK command line tools
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        rm cmdline-tools.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"

    - name: Convert class to DEX
      run: |
        export PATH=$HOME/android-sdk/build-tools/33.0.2:$PATH
        d8 --min-api 21 --output=./dex_output ZipUtil.class

    - name: Upload classes.dex
      uses: actions/upload-artifact@v4
      with:
        name: ziputil-dex
        path: ./dex_output/classes.dex
