name: Build Java to DEX

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pegar o código do repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Instalar Java 8
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # 3️⃣ Dar permissão de execução no d8
      - name: Make d8 executable
        run: chmod +x tools/d8

      # 4️⃣ Compilar todos os arquivos .java
      - name: Compile all Java files
        run: |
          mkdir -p bin
          find . -name "*.java" > sources.txt
          javac -source 1.8 -target 1.8 -d bin @sources.txt

      # 5️⃣ Converter .class para .dex usando d8 (shell expansion)
      - name: Convert classes to DEX
        run: |
          mkdir -p dex_output
          find bin -name "*.class" | xargs ./tools/d8 --min-api 21 --output=dex_output

      # 6️⃣ Upload do classes.dex como artefato
      - name: Upload classes.dex
        uses: actions/upload-artifact@v4
        with:
          name: dex-files
          path: ./dex_output/classes.dex
